# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#use_frameworks!
target 'TheBankCTV' do
    # Pods for TheBankCTV
    # React Native requirements
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    #'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
#    'ART',
#    'RCTActionSheet',
#    'RCTLinkingIOS',
#    'RCTGeolocation',
#    'RCTVibration',
#    'DevSupport',
#    'RCTBlob',
#    'RCTSettings',
    ]
    pod 'AppCenter/Crashes', '~> 1.14.0'
    pod 'AppCenter/Analytics', '~> 1.14.0'
    pod 'AppCenterReactNativeShared', '~> 1.13.0'
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'CodePush', :path => '../node_modules/react-native-code-push'   
    
    pod 'SwiftyJSON', '5.0'
    pod 'Charts', '3.3'
#    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
    pod 'RNSVG', :path => '../node_modules/react-native-svg'

#
#    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
#
#    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
#
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
#
#    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    platform :ios, '9.0'
    swift5 = ['Charts', 'SwiftyJSON']
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                if target.name == "React"
                    target.remove_from_project
                end
                if swift5.include?(target.name)
                    config.build_settings['SWIFT_VERSION'] = '5.0'
                end
            end
        end
    end
end


target 'TheBankCTV-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TheBankCTV-tvOS

  target 'TheBankCTV-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
